# Generated by Django 3.2.8 on 2021-10-21 03:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('year_of_birth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of birth')),
                ('year_of_death', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of death')),
                ('pha', models.PositiveIntegerField(blank=True, null=True, verbose_name='PHA')),
                ('pha_label', models.CharField(blank=True, max_length=10, null=True, verbose_name='PHA Label')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddc', models.CharField(blank=True, max_length=10, null=True, verbose_name='DDC')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Shelf',
                'verbose_name_plural': 'Shelves',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ddc', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='DDC')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Translator',
                'verbose_name_plural': 'Translators',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_id', models.PositiveIntegerField(unique=True, verbose_name='Physical ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Title')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('edition', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edition')),
                ('local', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page count')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('pha', models.CharField(blank=True, max_length=20, null=True, verbose_name='PHA')),
                ('observations', models.TextField(blank=True, max_length=2048, null=True, verbose_name='Observations')),
                ('authors', models.ManyToManyField(to='books.Author', verbose_name='Authors')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.collection', verbose_name='Collection')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.publisher', verbose_name='Publisher')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.shelf', verbose_name='Shelf')),
                ('subjects', models.ManyToManyField(to='books.Subject', verbose_name='Subjects')),
                ('translators', models.ManyToManyField(blank=True, to='books.Translator', verbose_name='Translators')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
