# Generated by Django 3.2.8 on 2021-10-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='year_of_death',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Year of death'),
        ),
    ]
