# Generated by Django 3.2.8 on 2021-10-26 17:14

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211021_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=isbn_field.fields.ISBNField(blank=True, max_length=28, null=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Page count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PHA'),
        ),
        migrations.AlterField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Description'),
        ),
    ]
