# Generated by Django 3.2.8 on 2021-11-03 01:17

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20211102_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[(books.models.BookStatus['archived'], 'Archived'), (books.models.BookStatus['lost_by_user'], 'Downed / Lost by user'), (books.models.BookStatus['defective'], 'Downed / Defective book'), (books.models.BookStatus['not_circulant'], 'Not circulant')], max_length=1, null=True, verbose_name='Status'),
        ),
    ]
