# Generated by Django 3.2.9 on 2021-11-18 00:16

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(books.models.BookStatus['circulant'], 'Circulant'), (books.models.BookStatus['archived'], 'Archived'), (books.models.BookStatus['lost_by_user'], 'Downed / Lost by user'), (books.models.BookStatus['defective'], 'Downed / Defective book'), (books.models.BookStatus['not_circulant'], 'Not circulant')], default=books.models.BookStatus['circulant'], max_length=255, verbose_name='Status'),
        ),
    ]
